### PR TITLE
readme: edit README.md and add CREDITS file

### PR DESCRIPTION
**Pull request by spacefault**
This commit edits the README.md file so that it's more concise and easier to understand. It also solves a couple of grammar mistakes and spelling errors. The credits were moved to a CREDITS file for easier machine parsing and better organization.

### CODE REVIEW

**Comment by xMqme** [comment]
:(

**Review by caernarferon — CHANGES_REQUESTED** [review]
Lets keep xmqmes current version

**Comment by xMqme** [comment]
> Lets keep xmqmes current version

no i like the new one
just copy the old one

**Comment by caernarferon** [comment]
> > Lets keep xmqmes current version
> 
> no i like the new one just copy the old one

my bad, i reopened

**Review by xMqme — APPROVED** [review]
buono

**Review by xMqme — APPROVED** [review]
good

**Review by xMqme — APPROVED** [review]
!

**Review by caernarferon — APPROVED** [review]
yes very amazing

**Comment by caernarferon** [comment]
merge it

**Pull request merged**
